name: 'Decrypt SOPS Secrets'
description: 'Run sops to decrypt secrets'
inputs:
  deployment_environment:
    description: 'The environment you want secrets decrypted for'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.deployment_environment }}
branding:
  icon: unlock
  color: red
